services:
  user-details-db:
    image: postgres:16
    restart: always
    environment:
       POSTGRES_DB : ${DB_NAME}
       POSTGRES_USER : ${DB_USERNAME}
       POSTGRES_PASSWORD : ${DB_PASSWORD}
    volumes:
      - user_details_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  user_details_data: