server:
  port: 8082

spring:
  datasource:
    url: "jdbc:postgresql://credit-story-db:5432/${CREDIT_STORY_DB_NAME:credit-stories}"
    username: "${CREDIT_STORY_USER:alexgls}"
    password: "${CREDIT_STORY_PASSWORD:AS04SERa1}"
